# Generated by Django 5.0.3 on 2024-03-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_alter_graphemployeeslist_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='time_tracking',
        ),
        migrations.DeleteModel(
            name='GraphTimeTracking',
        ),
    ]
