# Generated by Django 5.0.3 on 2024-03-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_alter_graph_employees_alter_graph_month_and_more'),
        ('tabel', '0002_alter_tabel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel',
            name='employees',
            field=models.ManyToManyField(related_name='tabel_employee', through='tabel.TabelEmployeesList', to='graph.employees', verbose_name='Работники'),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='month',
            field=models.CharField(choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], default=None, max_length=100, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='year',
            field=models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default=None, max_length=4, verbose_name='Год'),
        ),
    ]
