# Generated by Django 5.0.3 on 2024-03-11 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('type', models.CharField(choices=[('дни неявок', 'Дни Неявок'), ('дни явок', 'Дни Явок')], max_length=100, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='OilPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name Oil Place')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name Subdivision')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='WorkedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Tabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], default=None, max_length=100, verbose_name='Month')),
                ('year', models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default=None, max_length=4, verbose_name='Year')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservoir', to='graph.oilplace', verbose_name='Oil Place')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivision', to='graph.subdivision', verbose_name='Subdivision')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('tabel_number', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Tabel Number')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('middlename', models.CharField(max_length=50, verbose_name='Middle Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('tariff_category', models.IntegerField(verbose_name='Tariff Category')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='graph.job')),
                ('oil_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_place', to='graph.oilplace')),
                ('tabel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.tabel', verbose_name='Tabel ID')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('plan', 'Plan'), ('fact', 'Fact')], max_length=100, verbose_name='Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('worked_hours', models.CharField(max_length=5, verbose_name='Worked Hours')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.employees', verbose_name='EmployeeID')),
            ],
        ),
    ]
