# Generated by Django 5.0.3 on 2024-04-17 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], default=None, max_length=100, verbose_name='Месяц')),
                ('year', models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default=None, max_length=4, verbose_name='Год')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabel_reservoir', to='graph.oilplace', verbose_name='Месторождение')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabel_subdivision', to='graph.subdivision', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Согласованный Табель',
                'verbose_name_plural': 'Согласованные Табеля',
            },
        ),
        migrations.CreateModel(
            name='TabelApproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], default=None, max_length=100, verbose_name='Месяц')),
                ('year', models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default=None, max_length=4, verbose_name='Год')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabel_approved_reservoir', to='graph.oilplace', verbose_name='Месторождение')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabel_approved_subdivision', to='graph.subdivision', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Утвержденный Табель',
                'verbose_name_plural': 'Утвержденные Табеля',
            },
        ),
        migrations.CreateModel(
            name='TabelApprovedEmployeesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.employees')),
                ('tabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabel.tabelapproved')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.AddField(
            model_name='tabelapproved',
            name='employees',
            field=models.ManyToManyField(related_name='tabel_approved_employee', through='tabel.TabelApprovedEmployeesList', to='graph.employees', verbose_name='Работники'),
        ),
        migrations.CreateModel(
            name='TabelEmployeesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.employees')),
                ('tabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabel.tabel')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.AddField(
            model_name='tabel',
            name='employees',
            field=models.ManyToManyField(related_name='tabel_employee', through='tabel.TabelEmployeesList', to='graph.employees', verbose_name='Работники'),
        ),
        migrations.CreateModel(
            name='TimeTrackingTabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('worked_hours', models.CharField(default='0', max_length=5, null=True, verbose_name='Проработано часов')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.employees', verbose_name='Табельный Номер')),
            ],
            options={
                'verbose_name': 'Контроль времени работников Табеля',
                'verbose_name_plural': 'Контроль времени работников Табеля',
            },
        ),
    ]
