# Generated by Django 5.0.3 on 2024-05-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0012_alter_timetracking_unique_together'),
        ('tabel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabelapprovedtimetracking',
            options={'verbose_name': 'Контроль времени работников утверджающего Табеля', 'verbose_name_plural': 'Контроль времени работников утверджающего Табеля'},
        ),
        migrations.AlterModelOptions(
            name='timetrackingtabel',
            options={'verbose_name': 'Контроль времени работников согласованного Табеля', 'verbose_name_plural': 'Контроль времени работников согласованного Табеля'},
        ),
        migrations.AlterUniqueTogether(
            name='tabelapprovedtimetracking',
            unique_together={('date', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='timetrackingtabel',
            unique_together={('date', 'employee_id')},
        ),
    ]
