# Generated by Django 5.0.3 on 2024-03-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabel',
            options={'verbose_name': 'Табель', 'verbose_name_plural': 'Табеля'},
        ),
    ]
