# Generated by Django 5.0.3 on 2024-05-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel',
            name='status',
            field=models.CharField(choices=[('не утвержден', 'Не утвержден'), ('утвержден', 'Утвержден')], default='Не утвержден', max_length=20, verbose_name='Статус'),
        ),
    ]
