# Generated by Django 4.2.7 on 2024-04-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0002_tabelapprovedtimetracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabelapprovedemployeeslist',
            options={'verbose_name': 'Работники в графике', 'verbose_name_plural': 'Работники в графиках'},
        ),
    ]
