# Generated by Django 5.0.3 on 2024-05-20 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0009_alter_timetracking_unique_together'),
        ('tabel', '0002_tabel_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetrackingtabel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetrackingtabel',
            name='tabel_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tabel.tabel', verbose_name='Табель'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='timetrackingtabel',
            unique_together={('date', 'tabel_id', 'employee_id')},
        ),
    ]
