# Generated by Django 4.2.7 on 2024-04-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0003_alter_tabelapprovedemployeeslist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabelapprovedemployeeslist',
            options={'verbose_name': 'Работники в табеле', 'verbose_name_plural': 'Работники в табелях'},
        ),
        migrations.AlterModelOptions(
            name='tabelemployeeslist',
            options={'verbose_name': 'Работники в табеле', 'verbose_name_plural': 'Работники в табелях'},
        ),
    ]
