# Generated by Django 5.0.3 on 2024-05-20 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0009_alter_timetracking_unique_together'),
        ('tabel', '0003_alter_timetrackingtabel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tabelapprovedtimetracking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tabelapprovedtimetracking',
            name='tabel_approved_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tabel.tabelapproved', verbose_name='Утвержденный Табель'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tabelapprovedtimetracking',
            unique_together={('date', 'employee_id', 'tabel_approved_id')},
        ),
    ]
