# Generated by Django 5.0.3 on 2024-06-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0011_alter_graph_graph_json'),
        ('tabel', '0004_alter_tabelapprovedtimetracking_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel',
            name='cms',
            field=models.TextField(null=True, verbose_name='cms График'),
        ),
        migrations.AddField(
            model_name='tabel',
            name='graph_json',
            field=models.TextField(null=True, verbose_name='base64 json Графика'),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='status',
            field=models.CharField(default='Не согласованный', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterUniqueTogether(
            name='tabel',
            unique_together={('reservoir', 'subdivision', 'month', 'year')},
        ),
    ]
