# Generated by Django 5.0.3 on 2024-06-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0005_tabel_cms_tabel_graph_json_alter_tabel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel',
            name='cms',
            field=models.TextField(null=True, verbose_name='cms Табеля'),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='graph_json',
            field=models.TextField(null=True, verbose_name='base64 json Табеля'),
        ),
    ]
