# Generated by Django 5.0.3 on 2024-06-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0006_alter_tabel_cms_alter_tabel_graph_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabel',
            old_name='graph_json',
            new_name='tabel_json',
        ),
    ]
