# Generated by Django 5.0.3 on 2024-05-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='iin',
            field=models.CharField(default=1, max_length=13, unique=True, verbose_name='IIN'),
            preserve_default=False,
        ),
    ]
