# Generated by Django 5.0.3 on 2024-06-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_iin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middlename',
            field=models.CharField(default=1, max_length=100, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
