# Generated by Django 4.2.7 on 2024-04-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('type', models.CharField(choices=[('дни явок', 'Дни Явок'), ('дни неявок', 'Дни Неявок')], max_length=100, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Явка',
                'verbose_name_plural': 'Явки',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('tabel_number', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Табельный Номер Работника')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middlename', models.CharField(max_length=50, verbose_name='Отчество')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('tariff_category', models.IntegerField(verbose_name='Тарифная категория')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], default=None, max_length=100, verbose_name='Месяц')),
                ('year', models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default=None, max_length=4, verbose_name='Год')),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'Графики',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='OilPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название Месторождения')),
            ],
            options={
                'verbose_name': 'Месторождение',
                'verbose_name_plural': 'Месторождения',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название Подразделения')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='TimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('worked_hours', models.CharField(default='0', max_length=5, null=True, verbose_name='Проработано часов')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.employees', verbose_name='Табельный Номер')),
            ],
            options={
                'verbose_name': 'Контроль времени работников Графика',
                'verbose_name_plural': 'Контроль времени работников Графика',
            },
        ),
        migrations.CreateModel(
            name='GraphEmployeesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_graph_employee', to='graph.employees')),
                ('graph_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_graph_graph', to='graph.graph')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
                'unique_together': {('employee_id', 'graph_id')},
            },
        ),
        migrations.AddField(
            model_name='graph',
            name='employees',
            field=models.ManyToManyField(related_name='graph_employee', through='graph.GraphEmployeesList', to='graph.employees', verbose_name='Работники'),
        ),
        migrations.AddField(
            model_name='graph',
            name='reservoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_reservoir', to='graph.oilplace', verbose_name='Месторождение'),
        ),
        migrations.AddField(
            model_name='graph',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_subdivision', to='graph.subdivision', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='employees',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='graph.job', verbose_name='Работа'),
        ),
        migrations.AddField(
            model_name='employees',
            name='oil_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservoir', to='graph.oilplace', verbose_name='Месторождение'),
        ),
        migrations.AlterUniqueTogether(
            name='graph',
            unique_together={('reservoir', 'subdivision', 'month', 'year')},
        ),
    ]
