# Generated by Django 4.2.7 on 2024-03-29 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oilplace',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subdivision',
            name='description',
        ),
    ]
