# Generated by Django 5.0.3 on 2024-04-04 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='timetracking',
        ),
        migrations.DeleteModel(
            name='TimeTrackingGraph',
        ),
    ]
