# Generated by Django 4.2.7 on 2024-04-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_remove_oilplace_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='type',
            field=models.CharField(choices=[('дни явок', 'Дни Явок'), ('дни неявок', 'Дни Неявок')], max_length=100, verbose_name='Тип'),
        ),
    ]
