# Generated by Django 5.0.3 on 2024-05-16 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_alter_graph_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracking',
            name='graph',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='graph.graph', verbose_name='График'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graph',
            name='status',
            field=models.CharField(choices=[('не согласованный', 'Не согласованный'), ('согласованный', 'Согласованный')], default='Не согласованный', max_length=20, verbose_name='Статус'),
        ),
    ]
