# Generated by Django 5.0.3 on 2024-05-16 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_timetracking_graph_alter_graph_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetracking',
            unique_together={('date', 'graph')},
        ),
    ]
