# Generated by Django 5.0.3 on 2024-03-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_remove_graph_time_tracking_delete_graphtimetracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='employees',
            field=models.ManyToManyField(related_name='graph_employee', through='graph.GraphEmployeesList', to='graph.employees', verbose_name='Работники'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='month',
            field=models.CharField(choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], default=None, max_length=100, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='year',
            field=models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default=None, max_length=4, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='oilplace',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название Месторождения'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название Подразделения'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='worked_hours',
            field=models.CharField(default='0', max_length=5, verbose_name='Проработано часов'),
        ),
        migrations.AlterUniqueTogether(
            name='graph',
            unique_together={('reservoir', 'subdivision', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='timetracking',
            unique_together={('date', 'employee_id')},
        ),
    ]
