# Generated by Django 5.0.3 on 2024-04-22 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_remove_timetracking_employee_id_trackingemployee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='tracking',
        ),
        migrations.AddField(
            model_name='timetracking',
            name='employee_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='graph.employees', verbose_name='Табельный Номер'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TrackingEmployee',
        ),
    ]
