# Generated by Django 5.0.3 on 2024-04-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_remove_employees_tracking_timetracking_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetracking',
            unique_together={('date', 'employee_id')},
        ),
    ]
