# Generated by Django 4.2.7 on 2024-03-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_alter_timetracking_worked_hours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetracking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='month',
            field=models.IntegerField(choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], default=0),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='date',
        ),
    ]
