# Generated by Django 5.0.3 on 2024-05-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0007_alter_graphemployeeslist_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetracking',
            old_name='graph',
            new_name='graph_id',
        ),
        migrations.AlterUniqueTogether(
            name='timetracking',
            unique_together={('date', 'graph_id')},
        ),
    ]
