# Generated by Django 5.0.3 on 2024-05-20 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0008_rename_graph_timetracking_graph_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetracking',
            unique_together={('date', 'graph_id', 'employee_id')},
        ),
    ]
