# Generated by Django 5.0.3 on 2024-05-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0009_alter_timetracking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='cms',
            field=models.TextField(null=True, verbose_name='cms График'),
        ),
        migrations.AddField(
            model_name='graph',
            name='graph_json',
            field=models.TextField(null=True, verbose_name='json График'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='status',
            field=models.CharField(default='Не согласованный', max_length=20, verbose_name='Статус'),
        ),
    ]
