# Generated by Django 5.0.3 on 2024-03-12 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='oil_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservoir', to='graph.oilplace', verbose_name='Месторождение'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='reservoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_reservoir', to='graph.oilplace', verbose_name='Месторождение'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_subdivision', to='graph.subdivision', verbose_name='Подразделение'),
        ),
        migrations.CreateModel(
            name='GraphEmployeesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_graph_employee', to='graph.employees')),
                ('graph_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_graph_graph', to='graph.graph')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.AlterField(
            model_name='graph',
            name='employees',
            field=models.ManyToManyField(related_name='graph_employee', through='graph.GraphEmployeesList', to='graph.employees'),
        ),
        migrations.DeleteModel(
            name='Employees_Graph',
        ),
    ]
