# Generated by Django 5.0.3 on 2024-03-14 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_alter_employees_oil_place_alter_graph_reservoir_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graphemployeeslist',
            unique_together={('employee_id', 'graph_id')},
        ),
        migrations.CreateModel(
            name='GraphTimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_timetracking_graph', to='graph.graph')),
                ('timetracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_timetrakcing_timetracking', to='graph.timetracking')),
            ],
            options={
                'verbose_name': 'Контроль времени',
                'verbose_name_plural': 'Контроль времени',
                'unique_together': {('timetracking', 'graph_id')},
            },
        ),
        migrations.AddField(
            model_name='graph',
            name='time_tracking',
            field=models.ManyToManyField(related_name='graph_timetracking', through='graph.GraphTimeTracking', to='graph.timetracking'),
        ),
    ]
